### ISSUE TITLE
pomo raise error on opensuse 12.2 64bit

### ISSUE THREAD

**Issue by zlx** [tj/pomo#34]
Hello, I install pomo in my opensuse 12.2 64bit, but when i run pomo, it raise

``` sh
/home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/gems/commander-4.1.3/lib/commander/runner.rb:365:in `block in require_program': program version required (Commander::Runner::CommandError)
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/gems/commander-4.1.3/lib/commander/runner.rb:364:in `each'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/gems/commander-4.1.3/lib/commander/runner.rb:364:in `require_program'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/gems/commander-4.1.3/lib/commander/runner.rb:52:in `run!'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/gems/commander-4.1.3/lib/commander/delegates.rb:11:in `run!'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/gems/commander-4.1.3/lib/commander/import.rb:10:in `block in <top (required)>'
/home/soffolk/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require': cannot load such file -- libnotify (LoadError)
    from /home/soffolk/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/gems/pomo-2.1.1/lib/pomo/notifier/libnotify_notifier.rb:1:in `<top (required)>'
    from /home/soffolk/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/soffolk/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/gems/pomo-2.1.1/lib/pomo/notifier.rb:2:in `<top (required)>'
    from /home/soffolk/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/soffolk/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/gems/pomo-2.1.1/lib/pomo.rb:3:in `<top (required)>'
    from /home/soffolk/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/soffolk/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/gems/pomo-2.1.1/bin/pomo:5:in `<top (required)>'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/bin/pomo:19:in `load'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/bin/pomo:19:in `<main>'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/bin/ruby_noexec_wrapper:14:in `eval'
    from /home/soffolk/.rvm/gems/ruby-1.9.3-p327-falcon/bin/ruby_noexec_wrapper:14:in `<main>
```

Do anyone know why? Thank you

**Comment by zlx** [comment]
Resolved after i install libnotify

**Comment by stephenmckinney** [comment]
Are you referring to installing libnotify the package or libnotify the gem?

The gemspec should have required and thus installed the gem libnotify for you on Linux. See: [here](https://github.com/visionmedia/pomo/blob/master/pomo.gemspec#L28).
