### ISSUE TITLE
gem install pomo does not install properly

### ISSUE THREAD

**Issue by blurmonk** [tj/pomo#49]
Hi

I am on Debian I did the described install. This is the error log from the shell

thanks

/var/lib/gems/2.1.0/gems/commander-4.2.0/lib/commander/runner.rb:384:in `block in require_program': program version required (Commander::Runner::CommandError)
        from /var/lib/gems/2.1.0/gems/commander-4.2.0/lib/commander/runner.rb:383:in`each'
        from /var/lib/gems/2.1.0/gems/commander-4.2.0/lib/commander/runner.rb:383:in `require_program'
        from /var/lib/gems/2.1.0/gems/commander-4.2.0/lib/commander/runner.rb:51:in`run!'
        from /var/lib/gems/2.1.0/gems/commander-4.2.0/lib/commander/delegates.rb:8:in `run!'
        from /var/lib/gems/2.1.0/gems/commander-4.2.0/lib/commander/import.rb:10:in`block in <top (required)>'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- libnotify (LoadError)
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from /var/lib/gems/2.1.0/gems/pomo-2.1.3/lib/pomo/notifier/libnotify_notifier.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/pomo-2.1.3/lib/pomo/notifier.rb:2:in`<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from /var/lib/gems/2.1.0/gems/pomo-2.1.3/lib/pomo.rb:3:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/pomo-2.1.3/bin/pomo:5:in`<top (required)>'
        from /usr/local/bin/pomo:23:in `load'
        from /usr/local/bin/pomo:23:in`<main>'

**Comment by josiah14** [comment]
I just reproduced this error on my Ubuntu machine running ruby 2.1.5.

**Comment by rdark** [comment]
This is due to the libnotify gem not being installed, I guess because this gem is Linux specific. You can install manually it with `gem install libnotify`
Needs a platform-specific gemfile to 'fix', but then this means you can't include a Gemfile.lock (which isn't currently included anyway).

**Comment by thomaspaulmann** [comment]
I have also some trouble to install pomo under MacOS:
```
Could not find a valid gem 'pomo' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)
```

**Comment by zsebastian** [comment]
Adding to this, I needed to install ruby-dev to install libnotify. Not surprising, but I'm not ruby developer and it took some googling to figure it out.
